version: '3.8'

services:
  # Nginx served static DApp
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    
  # Backend that is being called by your smart contract through Hybrid Compute
  offchain-service:
    build:
      context: ./offchain
      dockerfile: ../Dockerfile
    ports:
      - "${OC_LISTEN_PORT:-1234}:${OC_LISTEN_PORT:-1234}"
    env_file: ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${OC_LISTEN_PORT:-1234}/hc" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: aa-hc-network

