version: "3.8"

services:
  # Backend that is being called by your smart contract through Hybrid Compute
  offchain-service:
    build:
      context: ./backend/offchain
      dockerfile: ../Dockerfile
    ports:
      - "${OC_LISTEN_PORT:-1234}:${OC_LISTEN_PORT:-1234}"
    env_file: ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${OC_LISTEN_PORT:-1234}/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Nginx served static DApp
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NETWORK=local # boba-sepolia | local
    image: bobanetwork/aa-hc-example-frontend
    ports:
      - "8000:80"
    restart: unless-stopped

  snap-account-abstraction-keyring:
    build:
      context: ./snap-account-abstraction-keyring
      dockerfile: Dockerfile
      args:
        - NETWORK=local # boba-sepolia | local
    image: bobanetwork/snap-account-abstraction-keyring
    ports:
      - "8080:8080"
      - "8001:8000"
    restart: unless-stopped


networks:
  default:
    name: aa-hc-network
