version: "3.8"

services:
  snap:
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: yarn start
  # Nginx served static DApp
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "8081:80"
    restart: unless-stopped

  # Backend that is being called by your smart contract through Hybrid Compute
  offchain-service:
    build:
      context: ./backend/offchain
      dockerfile: ../Dockerfile
    ports:
      - "${OC_LISTEN_PORT:-1234}:${OC_LISTEN_PORT:-1234}"
    env_file: ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${OC_LISTEN_PORT:-1234}/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  bundler:
    image: bobanetwork/rundler-hc #bobanetwork/bundler
    env_file: .env
    command: /usr/local/bin/rundler rpc
    depends_on:
      - geth
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 10s
    ports:
      - "3000:3000"
      - "8080:8080"

  geth:
    image: bobanetwork/geth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
    command:
      - --miner.gaslimit=12000000
      - --http
      - --http.api=personal,eth,net,web3,debug
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ws
      - --ws.api=personal,eth,net,web3,debug
      - --ws.addr=0.0.0.0
      - --ignore-legacy-receipts
      - --allow-insecure-unlock
      - --rpc.allow-unprotected-txs
      - --dev
      - --verbosity=2
      - --nodiscover
      - --maxpeers=0
      - --mine
      - --miner.threads=1
      - --networkid=1337

networks:
  default:
    name: aa-hc-network
