# Use an official Ubuntu base image
FROM --platform=linux/amd64 ubuntu:latest

# Set environment variables for Go
ENV GO_VERSION=1.22.2
ENV GO_TAR=go$GO_VERSION.linux-amd64.tar.gz
ENV GO_URL=https://golang.org/dl/$GO_TAR

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    git \
    make \
    python3 \
    python3-pip \
    build-essential \
    libc6-dev \
    libstdc++6 \
    curl && \
    rm -rf /var/lib/apt/lists/*

# Install Go
RUN curl -LO $GO_URL && \
    tar -C /usr/local -xzf $GO_TAR && \
    rm $GO_TAR

# Set Go environment variables
ENV PATH=$PATH:/usr/local/go/bin

# Clone the repository
RUN git clone https://github.com/bobanetwork/boba.git  

WORKDIR /boba

RUN git checkout wsdt/docker-test && \
    git submodule update --init --recursive
# Set the working directory to the root of the cloned repository

# Copy additional files if needed
COPY fix-op-erigon /fix-op-erigon

# Debug: List files and print the current directory
RUN echo "Current directory:" && pwd && ls -la

# Ensure 'make' is available and run the desired target
CMD ["sh", "-c", "pwd && ls -la && make devnet-hardhat-up"]
