name: Backend Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
        working-directory: ./backend
      - name: Run tests
        run: pnpm test
        working-directory: ./backend
        env:
          OC_LISTEN_PORT: ${{ vars.OC_LISTEN_PORT }}
          COINRANKING_API_KEY: ${{ secrets.COINRANKING_API_KEY }}
          OC_HYBRID_ACCOUNT: ${{ vars.OC_HYBRID_ACCOUNT }}
          ENTRY_POINTS: ${{ vars.ENTRY_POINT }}
          CHAIN_ID: ${{ vars.CHAIN_ID }}
          OC_PRIVKEY: ${{ secrets.OC_PRIVKEY }}
          HC_HELPER_ADDR: ${{ vars.HC_HELPER_ADDR }}
