name: Smart Contract Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Forge and Hardhat Tests
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies (root)
        run: pnpm install

      - name: Install dependencies (contracts)
        run: pnpm install
        working-directory: ./contracts

      - name: Run Forge tests
        run: forge test -vvv
        working-directory: ./contracts